apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  asknow:
    with:
      disallowLaunchByUser: false
      instructions: manual approval test using handler image from public prod ECR registry
      approvalInputs: |
        test:
          type: string
          required: true
        ch:
          type: choice
          options:
            - op1
          default: op1
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  hello:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          echo "test"
    needs: ask-now
