apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      version:
        type: string
      url:
        type: string
      digest:
        type: string
      app_id:
        type: string 
        default: 649308a1-7837-430f-955b-0d1dcc27c319     
jobs:
  build:
    steps:
      - uses: docker://ghcr.io/helmfile/helmfile:v1.1.2
        env:
          CBP_API_PAT: ${{ secrets.CBP_API_PAT }}
          CB_API_URL: ${{ cloudbees.api.url }}
          CB_RUN_ID: ${{ cloudbees.run_id }}
          CB_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
        run: |
          set -eo pipefail

          function get-artifact-id() {
            name=$1
            version=$2
            url=$3
            digest=$4
            app_id=$5

            echo "Find artifact with name: $name, version: $version, url: $url, digest: $digest in org $org_id ..."
            query_params="filter.names=${name}&filter.latestOnly=false&filter.searchText=${version}"
            
            echo "query params: $query_params, url: $CB_API_URL"
            response=$(curl --silent --show-error --fail-with-body  -X 'GET' "$CB_API_URL/v3/applications/${app_id}/artifactinfos?${query_params}" \
              -H "Authorization: Bearer $CBP_API_PAT" \
              -H 'Content-Type: application/json') || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to lookup artifact: $name, error: '$response'"
            else
              echo $response | jq  
              echo "looking for a match..."
              echo $response | jq '.artifacts'
              
              if [ "x$digest" == "x" ];
              then
                echo "wo digest"
                echo $response | jq '.artifacts[] | select(.version=="$version" and .url=="$url")'  
              else
                echo "with digest"
                echo $response | jq '.artifacts[] | select(.version=="$version" and .url=="$url" and .digest=="$digest")'
              fi
            fi  
          }

          get-artifact-id ${{ inputs.name }} ${{ inputs.version }} ${{ inputs.url }} ${{ inputs.digest }} ${{ inputs.app_id }}
