apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: https://github.com/urvashisingh/try-api-action
        name: Step One
        with:
          uri: /v1/organizations
          http-method: GET
      - uses: https://github.com/urvashisingh/try-api-action
        name: Step Two
        with:
          uri: /v1/organizations
          http-method: GET        
