apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: Say hello from push event
        if: ${{ cloudbees.event_name == 'push' }}
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Event payload ${{ cloudbees.event }}"    
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item
        with:
            content: |
              - item1
              - item2    
