apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      version:
        type: string
      url:
        type: string
      digest:
        type: string
      app_id:
        type: string 
        default: 649308a1-7837-430f-955b-0d1dcc27c319     
jobs:
  build:
    steps:
      - uses: docker://ghcr.io/helmfile/helmfile:v1.1.2
        env:
          CBP_API_PAT: ${{ secrets.CBP_API_PAT }}
          CB_API_URL: ${{ cloudbees.api.url }}
          CB_RUN_ID: ${{ cloudbees.run_id }}
          CB_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
        run: |
          set -eo pipefail

          function get-artifact-id() {
            local name=$1
            local version=$2
            local url=$3
            local digest=$4
            local app_id=$5
            local out_artifact_id=$6

            echo "Find artifact with name: $name, version: $version, url: $url, digest: $digest in org $org_id ..."
            query_params="filter.names=${name}&filter.latestOnly=false&filter.searchText=${version}"
            
            echo "query params: $query_params, url: $CB_API_URL"
            response=$(curl --silent --show-error --fail-with-body  -X 'GET' "$CB_API_URL/v3/applications/${app_id}/artifactinfos?${query_params}" \
              -H "Authorization: Bearer $CBP_API_PAT" \
              -H 'Content-Type: application/json') || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to lookup artifact: $name, error: '$response'"
              eval $out_artifact_id=""
            else
              echo $response | jq '.artifacts[]'
              
              if [ "$digest" = "null" ]; then
                echo "wo digest"
                artifact_id="$(echo $response | jq --raw-output --arg version $version --arg url $url '[.artifacts[] | select(.version==$version and .url==$url)] | .[0]')"  
              else
                echo "with digest"
                artifact_id="$(echo $response | jq --raw-output --arg version $version --arg url $url --arg digest $digest '[.artifacts[] | select(.version==$version and .url==$url and .digest==$digest)] | .[0]')"
              fi
              if [ "$artifact_id" = "null" ]; then
                eval $out_artifact_id="" 
              else
                eval $out_artifact_id="'$artifact_id'"
              fi
            fi  
          }

          get-artifact-id "${{ inputs.name }}" "${{ inputs.version }}" "${{ inputs.url }}" "${{ inputs.digest }}" "${{ inputs.app_id }}" art_id
          echo "Found artifactId: $art_id"
