apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_call:
    inputs:
      param1:
        type: string
        required: true
      dev_environment:
        type: string
        required: true
      us_dev_prop1:
        type: string
        required: true  
      us_dev_secret1:  
        type: string
        required: true  
      us_prod_prop1:
        type: string
        required: true  
      us_prod_secret1:  
        type: string
        required: true   
  workflow_dispatch:
    inputs:
      param1:
        type: string
        required: true
        default: param1
      dev_environment:
        type: string
        required: true
        default: us-dev
      us_dev_prop1:
        type: string
        required: true  
      us_dev_secret1:  
        type: string
        required: true
      us_prod_prop1:
        type: string
        required: true  
      us_prod_secret1:  
        type: string
        required: true  

jobs:
  dev:
    steps:
      - name: Deploy artifact
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying to env: ${{ inputs.dev_environment }}" 
          echo "Property (thru resource hierarchy) prop1: ${{ vars.prop1 }}"
          echo "Secret (thru resource hierarchy) secret 1 ${{ secrets.secret1 }}"
          echo "Env property as input us_dev_prop1: ${{ inputs.us_dev_prop1 }}"
          echo "Env secret as input us_dev_secret1: ${{ inputs.us_dev_secret1 }}"

  prod:
    needs: dev
    steps:
      - name: Deploy artifact
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying to env: ${{ inputs.prod_environment }}" 
          echo "Property (thru resource hierarchy) prop1: ${{ vars.prop1 }}"
          echo "Secret (thru resource hierarchy) secret 1 ${{ secrets.secret1 }}"
          echo "Env property as input us_prod_prop1: ${{ inputs.us_prod_prop1 }}"
          echo "Env secret as input us_prod_secret1: ${{ inputs.us_prod_secret1 }}"
